/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf 
Author: Hari (https://sketchfab.com/Hari31)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2020-lamborghini-sian-fkp-37-b5d0c81cb3624f6d80dcb56853e3352d
Title: 2020 Lamborghini Sián FKP 37
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.328}>
        <lineSegments geometry={nodes.Object_2.geometry} material={materials.Buttons} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Grille_4} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Grille_5} />
        <lineSegments geometry={nodes.Object_5.geometry} material={materials.Pribors} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Reverse_Lights} />
        <lineSegments geometry={nodes.Object_7.geometry} material={materials.Taillight_Glass} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.si_platelight} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Badges} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Brake_Lights} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Buttons} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Caliper_Badge} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Dark_Glass_2} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Day_Lights} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Engine} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Engine} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Grille_1} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Grille_2} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.Grille_6} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.High_Beams} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Interior} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.Interior} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.Interior} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Interior} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Interior_Stitches} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.Left_Signal} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Orange} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.Pribors} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.Right_Signal} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.SpecularTintA} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.Taillight_Glass} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.Taillights} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.mirror} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.si_grille3A} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.si_interior_o} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
